Add step to fail if provider is invalid

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -135,6 +135,11 @@ jobs:
         env:
           NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
 
+      - if: ${{ inputs.provider != 'vercel' && inputs.provider != 'netlify' }}
+        run: |
+          echo "Invalid provider"
+          exit 1
+
   cypress-ui-chrome-tests:
     if: ${{ needs.check-percy-token.outputs.token-exists == 'false' }}
     needs:
